name: 'Setup Metanorma'
description: 'Set up metanorma toolchain and add the command-line tools to the PATH'
author: 'Metanorma'
branding:
  icon: 'book-open'  
  color: 'blue'
inputs: 
  version:
    description: 'Version of a metanorma-cli ruby gem.'
    default: null
  snap-channel:
    description: 'Snapcraft channel, more details https://snapcraft.io/docs/channels'
    default: 'stable'
  choco-prerelase:
    description: Allow prerelases for chocolatey packages
    default: '' # false
runs:
  using: 'node20'
  main: 'dist/index.js'
